apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-server
data:
  useMockServerAccountService: "false"
  useMockServerTransferService: "false"
  useMockServerBalanceService: "false"
  useMockServerKYCService: "false"
  useMockServerCustomerService: "false"